"""Somatic failure categories used before caller execution."""

from __future__ import annotations

SOMATIC_FAILURE_CATEGORIES = {
    "somatic_config_error",
    "somatic_manifest_error",
    "duplicate_pair_id",
    "duplicate_tumor_sample",
    "invalid_normal_reuse",
    "subject_mismatch",
    "tumor_normal_identity_collision",
    "tumor_header_mismatch",
    "normal_header_mismatch",
    "ambiguous_sample_identity",
    "missing_tumor_input",
    "missing_normal_input",
    "missing_tumor_index",
    "missing_normal_index",
    "stale_tumor_index",
    "stale_normal_index",
    "tumor_reference_mismatch",
    "normal_reference_mismatch",
    "tumor_normal_reference_mismatch",
    "contig_order_mismatch",
    "contig_length_mismatch",
    "unsupported_input_type",
    "unsorted_alignment",
    "missing_read_group",
    "missing_sample_tag",
    "insufficient_tumor_coverage",
    "insufficient_normal_coverage",
    "extreme_coverage_imbalance",
    "invalid_purity",
    "invalid_contamination",
    "invalid_ploidy",
    "missing_required_metadata",
    "tumor_only_not_allowed",
    "tumor_only_acknowledgment_missing",
    "preflight_probe_error",
    "disk_space_error",
    "interrupted",
    "cancelled",
    "unknown",
}
